/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import islandScene from '../assets/3D/BestFloatingMayaIsland.compressed.glb'
import { a } from '@react-spring/three'

const Island = ({ isRotating, setIsRotating, setCurrentStage, position, rotation, scale, ...props }) => {
    const islandRef = useRef();
    const { gl, viewport } = useThree();
    const { nodes, materials } = useGLTF(islandScene);

    const lastX = useRef(0);
    const rotationSpeed = useRef(0);
    const dampingFactor = 0.95;

    const handlePointerDown = (e) => {
        e.stopPropagation();
        e.preventDefault();
        setIsRotating(true);

        const clientX = e.touches ? e.touches[0].clientX : e.clientX; 
        lastX.current = clientX;
    }

    const handlePointerUp = (e) => {
        e.stopPropagation();
        e.preventDefault();
        setIsRotating(false);
    }

    const handlePointerMove = (e) => {
    e.stopPropagation();
    e.preventDefault();

    if (isRotating) {
        const clientX = e.touches ? e.touches[0].clientX : e.clientX; 
        const delta = (clientX - lastX.current) / viewport.width;

        islandRef.current.rotation.y += delta * 0.05 * Math.PI;
        lastX.current = clientX;
        rotationSpeed.current = delta * 0.05 * Math.PI;
        
        // Add this for debugging
        console.log('Rotating island:', islandRef.current.rotation.y);
    }
}

    const handleKeyDown = (e) => {
        if (e.key === 'ArrowLeft') {
            if (!isRotating) setIsRotating(true);
            islandRef.current.rotation.y += 0.01 * Math.PI;
            rotationSpeed.current = 0.01 * Math.PI; // Set rotation speed for momentum
        } else if (e.key === 'ArrowRight') {
            if (!isRotating) setIsRotating(true); 
            islandRef.current.rotation.y -= 0.01 * Math.PI;
            rotationSpeed.current = -0.01 * Math.PI; // Set rotation speed for momentum
        }
    }

    const handleKeyUp = (e) => {
        if (e.key === 'ArrowLeft' || e.key === 'ArrowRight') {
            setIsRotating(false);
        }
    } 

    useFrame(() => {
        // Apply momentum/damping when not actively rotating
        if (!isRotating) {
            rotationSpeed.current *= dampingFactor;
            
            if (Math.abs(rotationSpeed.current) < 0.001) {
                rotationSpeed.current = 0; // Stop when speed is negligible
            } else {
                // Continue rotating with damped speed
                islandRef.current.rotation.y += rotationSpeed.current;
            }
        }

        // Stage detection
        if (setCurrentStage && islandRef.current) {
            const rotation = islandRef.current.rotation.y;
            const normalizedRotation = ((rotation % (2 * Math.PI)) + 2 * Math.PI) % (2 * Math.PI);

            switch (true) {
                case normalizedRotation >= 5.45 && normalizedRotation <= 5.85:
                    setCurrentStage(1);
                    break;
                case normalizedRotation >= 0.85 && normalizedRotation <= 1.3:
                    setCurrentStage(4);
                    break;
                case normalizedRotation >= 2.4 && normalizedRotation <= 2.6:
                    setCurrentStage(3);
                    break;
                case normalizedRotation >= 4.25 && normalizedRotation <= 4.75:
                    setCurrentStage(2);
                    break;
                default:
                    setCurrentStage(null);
            }
        }
    })

    useEffect(() => {
        const canvas = gl.domElement;
        
        canvas.addEventListener('pointerdown', handlePointerDown);
        canvas.addEventListener('pointerup', handlePointerUp);
        canvas.addEventListener('pointermove', handlePointerMove); 
        document.addEventListener('keydown', handleKeyDown);
        document.addEventListener('keyup', handleKeyUp); 

        return () => {
            canvas.removeEventListener('pointerdown', handlePointerDown);
            canvas.removeEventListener('pointerup', handlePointerUp);
            canvas.removeEventListener('pointermove', handlePointerMove); 
            document.removeEventListener('keydown', handleKeyDown);
            document.removeEventListener('keyup', handleKeyUp); 
        }
    }, [gl, handlePointerDown, handlePointerMove, handlePointerUp]);

    

  return (
    <a.group ref={islandRef} {...props} dispose={null}>
          <mesh
        geometry={nodes.Cube169.geometry}
        material={materials['Color Palette from imphenzia gradient X4.010']}
      />
      <mesh
        geometry={nodes.Rock4006.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Redmushroom4007.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Big_Grass.geometry}
        material={materials['Color Palette from imphenzia gradient X4.006']}
      />
      <mesh
        geometry={nodes.Base.geometry}
        material={materials['Color Palette from imphenzia gradient X4.011']}
      />
      <mesh
        geometry={nodes.The_Tip_of_the_banana001.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.The_Tip_of_the_banana008.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.The_Tip_of_the_banana009.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.The_Tip_of_the_banana010.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.The_Tip_of_the_banana011.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.The_Tip_of_the_banana012.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.The_Tip_of_the_banana013.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Plane002.geometry}
        material={materials['Material.001']}
      />
      <mesh
        geometry={nodes.Plane002_1.geometry}
        material={materials['Material.002']}
      />
      <mesh
        geometry={nodes.Plane002_2.geometry}
        material={materials['Material.003']}
      />
      <mesh
        geometry={nodes.Plane002_3.geometry}
        material={materials['Material.004']}
      />
      <mesh
        geometry={nodes.Plane002_4.geometry}
        material={materials['Material.005']}
      />
      <mesh
        geometry={nodes.Plane002_5.geometry}
        material={materials['Material.006']}
      />
      <mesh
        geometry={nodes.Plane002_6.geometry}
        material={materials['Material.007']}
      />
      <mesh
        geometry={nodes.Plane002_7.geometry}
        material={materials['Material.008']}
      />
      <mesh
        geometry={nodes.Plane002_8.geometry}
        material={materials['Material.009']}
      />
      <mesh
        geometry={nodes.Plane002_9.geometry}
        material={materials['Material.013']}
      />
      <mesh
        geometry={nodes.Plane002_10.geometry}
        material={materials['Material.014']}
      />
      <mesh
        geometry={nodes.Plane002_11.geometry}
        material={materials['Material.015']}
      />
      <mesh
        geometry={nodes.Plane002_12.geometry}
        material={materials['Material.016']}
      />
      <mesh
        geometry={nodes.Plane002_13.geometry}
        material={materials['Material.017']}
      />
      <mesh
        geometry={nodes.Cube1720.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube1720_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube1736.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube1736_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube1752.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube1752_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube371.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube371_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube391.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube391_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube415.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube415_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube433.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube433_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube449.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube449_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube465.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube465_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube518.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube518_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube544.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube544_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube845.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube845_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube866.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube866_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube894.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube894_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube922.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube922_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube950.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube950_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube966.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube966_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube982.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube982_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube998.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube998_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube1014.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube1014_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube6983.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube6983_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube6999.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube6999_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube7016.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube7016_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube7031.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube7031_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube7047.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube7047_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube7063.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube7063_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube7079.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube7079_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube7095.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube7095_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube7111.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube7111_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube7127.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube7127_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube7143.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube7143_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube7159.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube7159_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube7175.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube7175_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube7465.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube7465_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube7481.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube7481_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube7497.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube7497_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube7513.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube7513_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube7529.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube7529_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube7545.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube7545_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube7561.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube7561_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube7577.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube7577_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube7593.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube7593_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube7609.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube7609_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube7625.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube7625_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube7641.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube7641_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube7657.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube7657_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube7673.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube7673_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube7689.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube7689_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube7705.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube7705_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube7721.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube7721_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube7737.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube7737_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube7753.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube7753_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube7769.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube7769_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube7785.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube7785_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube7801.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube7801_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube8232.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube8232_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube8248.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube8248_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube8264.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube8264_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube8280.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube8280_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube8296.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube8296_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube8312.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube8312_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube8328.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube8328_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube8344.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube8344_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube8360.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube8360_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube8376.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube8376_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube8392.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube8392_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube8408.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube8408_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube8424.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube8424_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube8440.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube8440_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube8456.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube8456_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube8472.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube8472_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube8488.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube8488_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube8504.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube8504_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube8520.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube8520_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube8536.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube8536_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube8552.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube8552_1.geometry}
        material={materials['Gradient 2.002']}
      />
      <mesh
        geometry={nodes.Cube8568.geometry}
        material={materials['Gradient 1.002']}
      />
      <mesh
        geometry={nodes.Cube8568_1.geometry}
        material={materials['Gradient 2.002']}
      />
</a.group>
)
}

export default Island;